map_type: costmap

obstacle_range: 2.0 # 2.0
raytrace_range: 3.0 # 3.0

transform_tolerance: 0.2 # 0.0

robot_radius: 0.105 # 0.0
inflation_radius: 1.0 # 0.0
cost_scaling_factor: 3.0

observation_sources: scan

laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}